spring:
  application:
    name: cryptography
  
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptography-db
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: none

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/cryptography-db
    user: postgres
    password: 1234567
    schemas: public
    baseline-on-migrate: true

server:
  port: 8181

logging: 
  level: 
    org:
      flywaydb: DEBUG
