create table transaction (
    id bigint generated by default as identity,
    create_date timestamp(6),
    deleted boolean,
    update_date timestamp(6),
    credit_card_token varchar(255) not null,
    user_document varchar(255) not null,
    value numeric(10,2) not null,
    primary key (id)
);